version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: alv.ooo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local